import React from "react";
import {
  AllExercisesBpmChart,
  MonthByMonthChart,
  PracticeHeatmap,
  StreakStats,
  TimeDistributionChart,
  YearStats,
} from "./Summary";
import { formatFullDate } from "../utils";

interface PrintableReportProps {
  onReady?: () => void;
}

const PrintableReport = ({ onReady }: PrintableReportProps) => {
  // Notify parent when component is mounted and ready
  React.useEffect(() => {
    // Wait for all charts to render and styles to be applied
    const timer = setTimeout(() => {
      // Force a reflow to ensure all styles are computed
      const el = document.getElementById("printable-report");
      if (el) {
        void el.offsetHeight; // Trigger reflow
      }
      onReady?.();
    }, 3000);
    return () => clearTimeout(timer);
  }, [onReady]);

  return (
    <div
      id="printable-report"
      className="bg-gray-900 p-8 space-y-6"
      style={{ width: "1200px" }}
    >
      {/* Header */}
      <div className="text-center mb-6 pb-6 border-b-2 border-indigo-500">
        <h1 className="text-5xl font-bold text-white mb-3">
          🥁 Drum Practice Report
        </h1>
        <p className="text-lg text-gray-300">
          Generated on {formatFullDate(new Date())}
        </p>
      </div>

      {/* Key Statistics */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          📊 Overall Statistics
        </h2>
        <YearStats />
      </div>

      {/* Streak Stats */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          🔥 Practice Streaks
        </h2>
        <StreakStats />
      </div>

      {/* Month by Month Progress */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          📈 Monthly Progress
        </h2>
        <MonthByMonthChart />
      </div>

      {/* BPM Progress */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          🎵 BPM Development
        </h2>
        <AllExercisesBpmChart />
      </div>

      {/* Practice Calendar */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          📅 Practice Calendar
        </h2>
        <PracticeHeatmap />
      </div>

      {/* Time Distribution */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          ⏰ Practice Times
        </h2>
        <TimeDistributionChart />
      </div>

      {/* Footer */}
      <div className="mt-8 pt-6 border-t border-gray-700 text-center">
        <p className="text-gray-500 text-sm">
          Generated by Drum Practice Dashboard • Keep up the great work! 🥁
        </p>
      </div>
    </div>
  );
};

export default PrintableReport;
